version: "2.0"

services:
  jarredvardy_blog:
    build: .
    environment:
      - JEKYLL_ENV
    ports:
      - 4000:4000
    volumes:
      - .:/blog/
    #networks:
    #  - webdeploy_web-net

#networks:
#  webdeploy_web-net:
#    external: true