version: "2.0"

services:
  jarredvardy_blog:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - JEKYLL_ENV
    ports:
      - 4000:4000
    volumes_from:
    - webdeploy_blog:rw

volumes: 
  webdeploy_blog: